"""
shared/constants/__init__.py
"""

from shared.constants.pipeline import (
    RISK_SCORE_MIN,
    RISK_SCORE_MAX,
    RISK_THRESHOLD_WARNING,
    RISK_THRESHOLD_QUARANTINE,
    RISK_THRESHOLD_REJECT,
    ML_CONFIDENCE_HIGH,
    ML_CONFIDENCE_LOW,
    MAX_ATTACHMENT_SIZE_MB,
    MAX_RECIPIENTS_PER_EMAIL,
    SOURCE_SECURITY,
    SOURCE_ML,
    SOURCE_RISK,
    PHASE,
    IS_MOCK_MODE,
)

__all__ = [
    "RISK_SCORE_MIN",
    "RISK_SCORE_MAX",
    "RISK_THRESHOLD_WARNING",
    "RISK_THRESHOLD_QUARANTINE",
    "RISK_THRESHOLD_REJECT",
    "ML_CONFIDENCE_HIGH",
    "ML_CONFIDENCE_LOW",
    "MAX_ATTACHMENT_SIZE_MB",
    "MAX_RECIPIENTS_PER_EMAIL",
    "SOURCE_SECURITY",
    "SOURCE_ML",
    "SOURCE_RISK",
    "PHASE",
    "IS_MOCK_MODE",
]
